---
secret_files:
  api_nrec:
    path:  '/etc/pki/tls/certs/star.api.bgo.nrec.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  api_uh-iaas:
    path:  '/etc/pki/tls/certs/star.api.bgo.uh-iaas.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  star_nrec:
    path:  '/etc/pki/tls/certs/star.nrec.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  star_uh-iaas:
    path:  '/etc/pki/tls/certs/star.uh-iaas.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  console_nrec:
    path:  '/etc/pki/tls/certs/console.bgo.nrec.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  console_uh-iaas:
    path:  '/etc/pki/tls/certs/console.bgo.uh-iaas.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'

