---
secret_files:
  status:
    path:  '/etc/pki/tls/certs/status.iaas.intern.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  api:
    path:  '/etc/pki/tls/certs/api.iaas.intern.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  console:
    path:  '/etc/pki/tls/certs/console.local3.iaas.intern.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  star_api:
    path:  '/etc/pki/tls/certs/star.api.local3.iaas.intern.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
