secret_files:
  ca-cert:
    path:  '/etc/pki/tls/certs/cachain.pem'
    mode:  '0644'
    owner: 'root'
    group: 'root'
  cert:
    path:  '/etc/pki/tls/certs/ha02.uib.uhdc.no.cert.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  key:
    path:  '/etc/pki/tls/private/ha02.uib.uhdc.no.key.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  docs-cert:
    path:  '/etc/pki/tls/certs/docs.nrec.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  nrec-cert:
    path:  '/etc/pki/tls/certs/nrec.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  www-cert:
    path:  '/etc/pki/tls/certs/www.nrec.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  apps:
    path:  '/etc/pki/tls/certs/apps.uib.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  apps-admin:
    path:  '/etc/pki/tls/certs/apps-admin.uib.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  myprint:
    path:  '/etc/pki/tls/certs/myprint.uib.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
  storage-api:
    path:  '/etc/pki/tls/certs/storage-api.app.uib.no.pem'
    mode:  '0640'
    owner: 'root'
    group: 'root'
