---
location: bgo
domain: mgmt.bgo.uhdc.no

# This is used by the upgrade playbooks (lib/upgrade/<component>.yaml)
upgrade_puppet_env:
  keystone:   'yoga'
  neutron:    'yoga'
  nova:       'yoga'
  cinder:     'yoga'
  glance:     'yoga'
  horizon:    'yoga'
  ceilometer: 'yoga'
  designate:  'yoga'
