---
location: bgo
domain: mgmt.bgo.uhdc.no

# This is used by the upgrade playbooks (lib/upgrade/<component>.yaml)
upgrade_puppet_env:
  keystone:   'xena'
  neutron:    'wallaby'
  nova:       'wallaby'
  cinder:     'wallaby'
  glance:     'xena'
  horizon:    'wallaby'
  ceilometer: 'xena'
  designate:  'wallaby'
