---
location: osl
domain: mgmt.osl.uhdc.no

# This is used by the upgrade playbooks (lib/upgrade/<component>.yaml)
upgrade_puppet_env:
  keystone:   'xena'
  neutron:    'xena'
  nova:       'wallaby'
  cinder:     'xena'
  glance:     'xena'
  horizon:    'xena'
  ceilometer: 'xena'
  designate:  'xena'
